### ISSUE TITLE
Create dark variant

### ISSUE THREAD

**Issue by dbrodie** [nickbreaton/chrome-paper-gtk#3]
Would be nice to have a dark GTK Paper theme variant.

Thanks!

**Comment by nickbreaton** [comment]
@dbrodie Thanks for the suggestion, being that I don't actively use Paper GTK anymore, I didn't even think of that. 

I went ahead and created it. It can be found in the Chrome store at https://chrome.google.com/webstore/detail/paper-gtk-dark/kjpdhkfonpgopioenjbjoonbipifcaeo (as soon as Google publishes it).
